[allowlist]
  description = "Global Allowlist"

  # Ignore based on any subset of the file path
  paths = [
    # Ignore all example certs
    '''\/*.*\.json$''',

    # Ignore anything with the word funkymonkey anywhere in the path
    '''realms''',
    '''keycloak''',
    '''settings''',
    
  ]

  # Ignore based on any subset of the line
  regexes = [
    # Ignore lines containing pickles
    '''pickles''',
  ]